name: Mail Reminder

on:
  schedule:
    - cron: "0 6 * * *"  # her gün çalışır (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Script çalıştır
        run: python app.py
